#!/bin/zsh
# Generate a project-local, auditable cleanup dry run. It never deletes data.
# Applying a reviewed manifest is deliberately handled by apply_v1_cleanup.sh.
set -euo pipefail

root="${0:A:h:h}"
cd "$root"

usage() {
  print -u2 'usage: zsh Scripts/cleanup_v1_generated.sh --dry-run --output <new-project-relative-json>'
  exit 64
}

[[ "${1:-}" == "--dry-run" && "${2:-}" == "--output" && -n "${3:-}" && $# -eq 3 ]] || usage
output_relative="$3"
[[ "$output_relative" != /* && "$output_relative" != *".."* && "$output_relative" != */* && ! -e "$output_relative" && ! -L "$output_relative" ]] || {
  print -u2 'output must be a new non-symlink JSON file directly below the project root'
  exit 65
}

typeset -a candidate_paths
candidate_paths=("${(@f)$(find . -maxdepth 1 -type d \( -name '.codex-task-tmp-*' -o -name 'LatticeLens-UIFixture-*' \) -print | sed 's#^./##' | LC_ALL=C sort)}")
scratch="$(mktemp -d "$root/.codex-task-tmp-cleanup-dry-run-XXXXXX")"
trap '[[ -d "$scratch" ]] && find "$scratch" -depth -delete 2>/dev/null || true' EXIT

typeset -i index=0
for relative_entry in "${candidate_paths[@]}"; do
  candidate="$root/$relative_entry"
  canonical_path="${candidate:A}"
  [[ "$canonical_path" == "$root"/* && ! -L "$candidate" && -d "$candidate" ]] || {
    print -u2 "refusing unsafe cleanup candidate: $relative_entry"
    exit 65
  }

  bytes=$(( $(du -sk "$candidate" | awk '{print $1}') * 1024 ))
  process_check="available"
  process_in_use=false
  if (( $+commands[lsof] )); then
    lsof +D "$candidate" >/dev/null 2>&1 && process_in_use=true || true
  else
    process_check="unavailable"
  fi

  case "$relative_entry" in
    .codex-task-tmp-*)
      reason="task-local scratch generated by development or verification"
      retention_class="ephemeral_task_scratch"
      ;;
    LatticeLens-UIFixture-*)
      reason="process-local fixture UI store generated by XCTest"
      retention_class="ephemeral_ui_fixture"
      ;;
    *)
      print -u2 "refusing unexpected cleanup name: $relative_entry"
      exit 65
      ;;
  esac

  allowed=true
  [[ "$process_check" == "available" && "$process_in_use" == false ]] || allowed=false
  jq -n \
    --arg relative_path "$relative_entry" \
    --arg canonical_path "$canonical_path" \
    --arg reason "$reason" \
    --arg retention_class "$retention_class" \
    --arg process_check "$process_check" \
    --argjson bytes "$bytes" \
    --argjson symlink false \
    --argjson process_in_use "$process_in_use" \
    --argjson allowed "$allowed" \
    '{relativePath:$relative_path,canonicalPath:$canonical_path,type:"directory",bytes:$bytes,symlink:$symlink,reason:$reason,retentionClass:$retention_class,processCheck:$process_check,processInUse:$process_in_use,allowedToDelete:$allowed}' \
    > "$scratch/entry-${index}.json"
  (( index += 1 ))
done

entries_json="$(jq -s '.' "$scratch"/entry-*.json 2>/dev/null || print '[]')"
jq -n \
  --arg generated_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --arg project_root "$root" \
  --argjson entries "$entries_json" \
  '{schema_version:"latticelens-cleanup-v1.0",mode:"dry_run",generatedAtUTC:$generated_at,projectRoot:$project_root,entries:$entries,allowed_relative_paths:[$entries[] | select(.allowedToDelete == true) | .relativePath],summary:{candidateCount:($entries|length),candidateBytes:([$entries[].bytes] | add // 0),allowedCount:([$entries[] | select(.allowedToDelete == true)] | length),blockedCount:([$entries[] | select(.allowedToDelete != true)] | length)},forbidden:["Application Support","Keychain","active libraries","historical Release-v*","xcresult","user Research Bundles","/Applications/LatticeLens.app"]}' \
  > "$output_relative"
print -- "$output_relative"
